includes:
  - dependencies: ./dependencies.yaml
  - test: ./tasks/test.yaml
  - create: https://raw.githubusercontent.com/defenseunicorns/uds-common/v0.8.0/tasks/create.yaml
  - publish: https://raw.githubusercontent.com/defenseunicorns/uds-common/v0.8.0/tasks/publish.yaml

tasks:
  - name: build-bundle
    description: Build the bundle
    actions:
      - task: dependencies:create
      - task: create:test-bundle
        with:
          path: ${BUNDLE_PATH}

  - name: test-bundle
    description: Test the built bundle
    actions:
      - task: setup:k3d-test-cluster
      - task: deploy:test-bundle
        with:
          path: ${BUNDLE_PATH}
      - task: test:test-swf-bundle

  - name: publish-bundle
    description: Publish the bundle
    actions:
      - task: publish:test-bundle
        with:
          path: ${BUNDLE_PATH}
          # x-release-please-start-version
          version: "0.2.2"
          # x-release-please-end
