variables:
  - name: FLAVOR
    default: upstream
  - name: TARGET_REPO
    default: ghcr.io/defenseunicorns/packages/uds

tasks:
  - name: latest-bundle-release
    inputs:
      path:
        description: Path relative to the repositories root where the bundle things happen
        default: .
      spoof_release:
        description: Whether to spoof the pulled bundle version to the current repo version
        default: "false"
    actions:
      - description: Get the current uds bundle name
        cmd: cat ${{ .inputs.path }}/uds-bundle.yaml | yq .metadata.name
        setVariables:
          - name: BUNDLE_NAME
      - description: Get latest tag version from OCI
        cmd: ./uds zarf tools registry ls ${TARGET_REPO}/${BUNDLE_NAME} | grep ${FLAVOR} | sort -V | tail -1
        setVariables:
          - name: LATEST_VERSION
      - description: Pull the latest package release
        cmd: ./uds zarf package pull oci://${TARGET_REPO}/${BUNDLE_NAME}:${LATEST_VERSION} --no-progress -o ${{ .inputs.path }}
      # TODO (@WSTARR): This is currently needed to get around the chicken+egg condition when release please updates the version in GH
      - description: Spoof the latest release to the current version
        cmd: |
          if [ ${{ .inputs.spoof_release }} != "false" ]; then
            CURRENT_VERSION=$(cat {{ .inputs.path }}/uds-bundle.yaml | yq .metadata.version)
            CURRENT_PKG_NAME=$(cat {{ .inputs.path }}/uds-bundle.yaml | yq .metadata.name)
            test -f {{ .inputs.path }}/uds-bundle-${CURRENT_PKG_NAME}-${UDS_ARCH}-${CURRENT_VERSION}.tar.zst || mv {{ .inputs.path }}/uds-bundle-${CURRENT_PKG_NAME}-${UDS_ARCH}-*.tar.zst {{ .inputs.path }}/uds-bundle-${CURRENT_PKG_NAME}-${UDS_ARCH}-${CURRENT_VERSION}.tar.zst
          fi
