# Source: bigbang/templates/gitlab/secret-objectstore.yaml
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-object-store
  namespace: gitlab
type: kubernetes.io/opaque
stringData:
  connection: |-
    provider: AWS
    region: minio
    aws_access_key_id: ###ZARF_VAR_ACCESS_KEY###
    aws_secret_access_key: ###ZARF_VAR_SECRET_KEY###
    endpoint: "http://minio.dev-minio.svc.cluster.local:9000"
    aws_signature_version: 4
    path_style: true
  registry: |-
    s3:
      bucket: uds-gitlab-registry
      accesskey: ###ZARF_VAR_ACCESS_KEY###
      secretkey: ###ZARF_VAR_SECRET_KEY###
      regionendpoint: "http://minio.dev-minio.svc.cluster.local:9000"
      region: minio
      aws_signature_version: 4
      path_style: true
  backups: |-
    [default]
    access_key = ###ZARF_VAR_ACCESS_KEY###
    secret_key = ###ZARF_VAR_SECRET_KEY###
    host_base = http://minio.dev-minio.svc.cluster.local:9000
    host_bucket = http://minio.dev-minio.svc.cluster.local:9000
    bucket_location = minio
    multipart_chunk_size_mb = 128
    use_https = False
