name: Metadata

on:
  # This workflow is triggered on pull requests to the main branch.
  pull_request:
    branches: [main]
    types: [milestoned, opened, edited, synchronize]


jobs:
  validate:
    name: Validate
    uses: defenseunicorns/uds-common/.github/workflows/commitlint.yaml@f0164622ffc2007e96a0e1deaa3f5064db04b148 # v1.1.0
