name: Metadata

on:
  # This workflow is triggered on pull requests to the main branch.
  pull_request:
    branches: [main]
    types: [milestoned, opened, edited, synchronize]


jobs:
  validate:
    name: Validate
    uses: defenseunicorns/uds-common/.github/workflows/commitlint.yaml@9c4786868c2d6950fa0fd2249b08632526da5664 # v0.3.7
